@startuml Constructorabler
abstract class Constructorable 

Constructorable *--> "*" TypeParameter : genericParameter 
Constructorable *--> "   \n\n*" Annotation : modAnnotations 
Constructorable *--> "\n*" AccessModifier : accessModifiers
Constructorable *--> "*" ParameterSeqLike : parameterSeqs

hide class circle
hide class members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
}

@enduml 