@startuml Constructorabler
abstract class Constructorable 

Constructorable o-down-> " *  " TypeParameter : genericParameter 
Constructorable o-down-> "   \n\n  *" Annotation : modAnnotations 
Constructorable o-up-> "  \n*" AccessModifier : accessModifiers
Constructorable o-up-> " *  " ParameterSeqLike : parameterSeqs

hide circle
hide class members

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
}

@enduml 