@startuml Defines 
abstract class Defines {
    \n
    \n
    \n 
}

Defines *--left> "*" ValDef : vals 
Defines *--up> " *  " DefDef : "\n defs" 
Defines *--> "*" VarDef : vars
Defines *--> " *  " TypeDef : types
Defines *--> "    \n*" Class : classes
Defines *--> "\n*" Enum  : enums 
Defines *--up> " *  \n" Object : "\nobjects" 
Defines *--right> "*" Given : givens 

hide circle
hide members 

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
}

@enduml 