@startuml Defineable 
abstract class Definable {
    identifier:String
}

Definable --> "    \n*" Annotation : annotations 
Definable --> "      \n*" Modifier : modifiers

hide class circle
hide class members
hide Definable methods

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
}

@enduml 