@startuml Class

abstract class Defineable
abstract class Constructorable 
abstract class Defines 

class Class extends Defineable, Constructorable, Defines {
    isCaseClass : Boolean 
    isTrait : Boolean 
    isSuperTrait : Boolean 
}

Class --> "*" Class : innerClasses\n {refines classes}
Class --> "*" Import : imports
Class --> "*" Export : exports 
Class *--left> "0..1  " Inherit : inherits
Class *--> "*" Extension : "extensions"
Class *--> "*" ClassParameterSeqLike : parameterSeqs \n{refines parameterSeqs}

hide class circle
hide class methods
hide Defineable members
hide Constructorable members 
hide Defines members 

skinparam defaultFontName Source Code Pro

skinparam ClassStereotypeFontColor #1b1f23

skinparam class {
    BackgroundColor White
    BorderColor #1b1f23
    ArrowColor #1b1f23
    FontColor #6f42c1
}

skinparam note {
    BackgroundColor White
    BorderColor #1b1f23
    ArrowColor #1b1f23
    FontColor #d73a49
}

skinparam stereotype {
    FontColor #d73a49
}

hide circle
@enduml