
abstract class uml.StereotypeElement <<trait>> 


abstract class uml.StereotypeElement <<trait>>
abstract class uml.TopLevelElement <<trait>>
abstract class uml.PackageBodyElement <<trait>>

    class uml.Package << caseclass >>{
        <<ctor pos=1>> packageBodyElements : List<PackageBodyElement>
        <<ctor pos=1>> stereotype : List<Stereotype>
        <<ctor pos=1>> namespace : Entry 
    -- <<scalaclass>> --
        isSealed
    }

uml.TopLevelElement <|-- uml.Package 
uml.PackageBodyElement <|-- uml.Package 
uml.StereotypeElement <|-- uml.Package 

hide circle  
skinparam defaultFontName Source Code Pro

skinparam ClassStereotypeFontColor #1b1f23

skinparam class {
    BackgroundColor White
    BorderColor #1b1f23
    ArrowColor #1b1f23
    FontColor #6f42c1
}

skinparam note {
    BackgroundColor White
    BorderColor #1b1f23
    ArrowColor #1b1f23
    FontColor #d73a49
}


skinparam stereotype {
    FontColor #d73a49
}