@startuml Scala Profile 
package "<<profile>> Scala" #00 {

    '---------------------------------------------------
    'Metaclasses 
    class "Class" <<metaclass>>
    class "Operation" <<metaclass>>
    class "Association" <<metaclass>>
    class "Property" <<metaclass>>
    class "Parameter" <<metaclass>>
    class "Interface" <<metaclass>>
    class "Package" <<metaclass>>
    class "Specialization" <<metaclass>>

    '---------------------------------------------------
    'Interfaces 

    abstract class AccessModifierElement {
        isPrivateAccess : boolean 
        privateAccessModifier : String 
        isProtectedAccess : boolean 
        protectedAccessModifier : String
    }

    abstract class ModifierElement {
        isFinal : boolean 
        isImplicit : boolean 
        isInline : boolean 
        isLazy : boolean 
        isOpaque : boolean 
        isOpen : boolean 
        isOverride : boolean 
        isSealed : boolean 
    }

    hide ModifierElement methods 

    '---------------------------------------------------
    'Class Stereotype 
    class ScalaClass <<stereotype>> extends ModifierElement, AccessModifierElement

    class Trait <<stereotype>> {
        isSuper : boolean 
    } 
    class CaseClass <<stereotype>>
    class Type <<stereotype>> {
        isOpaque:Boolean 
    }
    Class <-- ScalaClass
    ScalaClass <-- Trait 
    ScalaClass <-- CaseClass 

    '---------------------------------------------------
    'Class Properties 

    class Var <<stereotype>> extends ModifierElement, AccessModifierElement
    class Val <<stereotype>> extends ModifierElement, AccessModifierElement
    class TypeRep <<stereotype>> extends ModifierElement, AccessModifierElement

    Property <-- Var 
    Property <-- Val 
    Property <-- TypeRep 
    Property <-- Ctor 

    ScalaClass <-- Val 
    ScalaClass <-- Var 
    ScalaClass <-- Type 

    '---------------------------------------------------
    'Class Parameter

    class Using <<stereotype>> 
    class Implicit <<stereotype>>
    class ByName <<stereotype>>
    class Repeated <<stereotype>> 

    Parameter <-- Using
    Parameter <-- Implicit
    Parameter <-- ByName   
    Parameter <-- Repeated 

    '---------------------------------------------------
    ' Associations

    class given <<stereotype>> 
    class Ctorbind <<stereotype>> {
        vals : String [*]
    }
    class Objectdef <<stereotype>>
    Association <-- GivenAs
    Association <-- Ctorbind
    Association <-- Objectdef 

    '---------------------------------------------------
    ' Operations 

    class Def <<stereotype>> extends ModifierElement

    Operation <-- "{required}" Def
    ScalaClass <-- Def 

    class ParamSeq <<stereotype>>

    ScalaClass <-- ParamSeq
    
    '---------------------------------------------------
    'Class Constructor 
    class Ctor <<stereotype>> extends AccessModifierElement {
        pos : int [0..1]
    }

    Operation <-- Ctor
    

    '---------------------------------------------------
    'Extensions 
    class Extension <<stereotype>> 
    Interface <-- Extension 

    '---------------------------------------------------
    'Annotations 

    class Annotated <<stereotype>> {
        annotations:String [1..*]
    }

    class " Parameter " <<metaclass>>
    class " Operation " <<metaclass>>
    class " Class " <<metaclass>> 

    Type -[hidden]- Annotated
    Annotated --> " Parameter "
    Annotated --> " Operation "
    Annotated --> " Class " 

    '---------------------------------------------------
    'Enums 

    class ScalaEnum <<stereotype>> 
    class Case <<stereotype>> 

    ScalaClass <-- ScalaEnum
    ScalaClass <-- Case

    '---------------------------------------------------
    'Objects 

    class Object <<stereotype>> 
    ScalaClass <-- Object 

    '---------------------------------------------------
    'Given
    
    class GivenInstance <<stereotype>>
    class GivenAlias <<stereotype>>  

    ScalaClass <-- GivenInstance 
    ScalaClass <-- GivenAlias 

    '---------------------------------------------------
    'Packages

    class Packageobject <<stereotype>>

    Package <-- Packageobject

    class Companion <<stereotype>>

}

hide class circle
hide class methods 
hide <<metaclass>> members 
hide Operation members 
hide Extension members 

skinparam linetype ortho

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
}

@enduml 