@startuml

package Scala <<profile>> {

    class Attribute <<metaclass>>
    class Association <<metaclass>>
    class Operation <<metaclass>> 

    abstract class AccessModifierElement {
        isObjectPrivate : boolean 
        isClassPrivate : boolean  
        isQualifiedPrivate : boolean 
        privateAccessQualid : String 
        isObjectProtected : boolean
        isQualifiedProtected : boolean
        protectedAccessQualid : String
    }

    class Ctor <<stereotype>> {
        pos:int [0..1]
    }

    Operation <-- Ctor 
    Attribute <-- Ctor 
    Association <-- Ctor 
    Ctor --|> AccessModifierElement
}

hide class circle
hide Attribute members 
hide Association members 
hide Ctor methods 
hide AccessModifierElement methods
hide <<metaclass>> members 

skinparam defaultFontName Source Code Pro

skinparam ClassStereotypeFontColor #1b1f23

skinparam class {
    BackgroundColor White
    BorderColor #1b1f23
    ArrowColor #1b1f23
    FontColor #6f42c1
}

skinparam note {
    BackgroundColor White
    BorderColor #1b1f23
    ArrowColor #1b1f23
    FontColor #d73a49
}


skinparam stereotype {
    FontColor #d73a49
}

hide circle

@enduml 