@startuml

package "<<profile>> Scala" #00 {
    class Class <<metaclass>>
    class ScalaClass <<stereotype>> 
    class Trait <<stereotype>> {
        isSuper:boolean
    }
    class CaseClass <<stereotype>> 

    Class <-- ScalaClass
    ScalaClass <-- CaseClass 
    ScalaClass <-- Trait 

}

hide class circle
hide class methods 
hide <<metaclass>> members 
hide CaseClass members 
hide ScalaClass members 

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
}

@enduml 