@startuml Multiple ParameterSeqs

' trait Universe {
'  trait Needle {
'    def combine(other: Needle): Needle
'  }
' }
'
' def combine(u: Universe)(n1: u.Needle, n2: u.Needle) = n1 combine n2

class Universe <<trait>> 
class Needle <<trait>> {
    + combine (other:Needle): Needle
}

Universe +-- Needle 

class Wrapper <<object>> {
    {static}combine(u:Universe)(<<dependent ids=["u"]>>n1:Needle,<<dependent ids=["u"]>>n2:Needle):<<dependent ids = ["u"]>> Needle
}

hide class circle
hide <<paramSeq>> methods

skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
}
@enduml