@startuml

package uml {
    abstract class uml.TopLevelElement <<trait>>
    abstract class uml.NamedElement <<trait>>
    abstract class uml.PackageBodyElement <<trait>>
}
package uml::externalReferences{
    class uml::externalReferences.ClassDefRef << caseclass >> {
        classtype : ClassType,
        name : String,
        namespace : Entry,
        templateParameter : List<String>,
        oStat : Option<Stat>
    }
}

uml.TopLevelElement <|-up- uml::externalReferences.ClassDefRef 
uml.NamedElement <|-up- uml::externalReferences.ClassDefRef 
uml.PackageBodyElement <|-up- uml::externalReferences.ClassDefRef 

hide circle 
hide <<trait>> members 
skinparam defaultFontName Source Code Pro

skinparam ClassStereotypeFontColor #1b1f23

skinparam class {
    BackgroundColor White
    BorderColor #1b1f23
    ArrowColor #1b1f23
    FontColor #6f42c1
}

skinparam note {
    BackgroundColor White
    BorderColor #1b1f23
    ArrowColor #1b1f23
    FontColor #d73a49
}


skinparam stereotype {
    FontColor #d73a49
}

@enduml