@startuml need_to_find_id
package app::frontend::processor{
    class app::frontend::processor.UMLDiagramProcessor << caseclass >>{
        outputPath : String
        filesPath : String  
        isVerbose : Boolean  
        isTextual : Boolean  
        name : String
    }
    class app::frontend::processor.$Processor << object >>{
        apply (commands : List<Command>) : Processor 
    }
    abstract class app::frontend::processor.Processor << trait >>{
        execute () : Unit 
    
    }
    class app::frontend::processor.HelpProcessor << caseclass >>{
        helpCmd : Help
    }
    class app::frontend::processor.GithubUMLDiagramProcessor << caseclass >>{
        outputPath : String
        githubConfigPath : String  
        isVerbose : Boolean  
        isTextual : Boolean  
        name : String
    }
}
app::frontend::processor.Processor .. app::frontend::processor.$Processor : <<companion>>
app::frontend::processor.Processor <|-- app::frontend::processor.GithubUMLDiagramProcessor 
app::frontend::processor.Processor <|-- app::frontend::processor.HelpProcessor 
app::frontend::processor.Processor <|-- app::frontend::processor.UMLDiagramProcessor 

hide circle 
skinparam defaultFontName Source Code Pro

skinparam ClassStereotypeFontColor #1b1f23

skinparam class {
    BackgroundColor White
    BorderColor #1b1f23
    ArrowColor #1b1f23
    FontColor #6f42c1
}

skinparam note {
    BackgroundColor White
    BorderColor #1b1f23
    ArrowColor #1b1f23
    FontColor #d73a49
}


skinparam stereotype {
    FontColor #d73a49
}
@enduml