@startuml
package ModelProfile <<profile>> {
    class Class <<metaclass>> 
    class Node <<stereotype>> {
        location:String 
    }
    class MainNode <<stereotype>> 
    class Association <<metaclass>>
    class Edge <<stereotype>>
    class LocalEdge <<stereotype>> 

    Class <-- Node  
    Node <|-- MainNode
    Association <-- Edge
    Association <-- LocalEdge

hide circle 
    skinparam defaultFontName Source Code Pro

skinparam ClassStereotypeFontColor #1b1f23

skinparam class {
    BackgroundColor White
    BorderColor #1b1f23
    ArrowColor #1b1f23
    FontColor #6f42c1
}

skinparam note {
    BackgroundColor White
    BorderColor #1b1f23
    ArrowColor #1b1f23
    FontColor #d73a49
}


skinparam stereotype {
    FontColor #d73a49
}

}
@enduml